// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoBanco.Api.Data;

#nullable disable

namespace ProjetoBanco.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_AGENCIAS", (string)null);
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("TB_CLIENTES", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Contratacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("TB_CONTRATACOES", (string)null);
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUTOS", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.PessoaFisica", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Domain.Cliente");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.PessoaJuridica", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Domain.Cliente");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Emprestimo", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Domain.Produto");

                    b.Property<int>("PrazoDias")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasDiscriminator().HasValue("EMPRESTIMO");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Domain.Produto");

                    b.Property<decimal>("TaxaMDR")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasDiscriminator().HasValue("MAQUINA");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.ReceberSalario", b =>
                {
                    b.HasBaseType("ProjetoBanco.Api.Domain.Produto");

                    b.Property<string>("EmpresaConvenio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasDiscriminator().HasValue("SALARIO");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Cliente", b =>
                {
                    b.HasOne("ProjetoBanco.Api.Domain.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Contratacao", b =>
                {
                    b.HasOne("ProjetoBanco.Api.Domain.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoBanco.Api.Domain.Produto", "Produto")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("ProjetoBanco.Api.Domain.Produto", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
